apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: craftedspecially-api
  namespace: default
spec:
  parentRefs:
    - name: craftedspecially-gateway
      namespace: envoy-gateway-system
      kind: Gateway
      sectionName: https
  # TODO: replace with the actual domain name.
  hostnames:
    - "" # e.g. api.craftedspecially.example.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: craftedspecially-api
          port: 8080
          # TODO: update port to match the Service port exposed by CraftedSpecially.Api
