apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: envoy-gateway-controller-pdb
  namespace: envoy-gateway-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      control-plane: envoy-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: envoy-gateway-proxy-pdb
  namespace: envoy-gateway-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      gateway.envoyproxy.io/owning-gateway-name: craftedspecially-gateway
      gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-system
