FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /App

# Copy everything
COPY ./Common/Application.Common/ ./Common/Application.Common/
COPY ./Common/Domain.Common/ ./Common/Domain.Common/
COPY ./Services/Catalog/ ./Services/Catalog/

WORKDIR /App/Services/Catalog

# Restore as distinct layers
RUN dotnet restore

RUN dotnet test

# Build and publish a release
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0

ENV ASPNETCORE_URLS=http://+:8080

WORKDIR /App
COPY --from=build-env /App/Services/Catalog/out .
ENTRYPOINT ["dotnet", "WebApi.dll"]
