apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crafted-specially
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tom171296/CraftedSpecially.git
    targetRevision: main
    path: infra/k8s/crafted-specially
  destination:
    server: https://kubernetes.default.svc
    namespace: crafted-specially
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
