apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httproutes
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tom171296/CraftedSpecially.git
    targetRevision: issues/agentic-workflow
    path: infra/k8s/routes
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
