apiVersion: v1
kind: Service
metadata:
  name: crafted-specially-api
  namespace: crafted-specially
spec:
  type: ClusterIP
  selector:
    app: crafted-specially
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
